WebApp/ViewModels/TaskViewModel.cs
namespace WebApp.ViewModels
{
    using System;

    public class TaskViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime AllowSubmissionFromDate { get; set; }

        public DateTime DueDate { get; set; }

        public DateTime GradingDate { get; set; }

        public int MaxWorks { get; set; }

        public string CourseName { get; set; }
    }
}

WebApp/Controllers/Submission/SubmissionController.cs
namespace WebApp.Controllers.Submission
{
    using Microsoft.AspNetCore.Mvc;
    using Domain.Services;
    using Domain.UnitOfWork;
    using System.Collections.Generic;
    using Domain.Entities;
    using AutoMapper;
    using Domain.Services.Rubric;
    using System.Linq;
    using ViewModels;
    using Domain.Services.CardinalGrade;
    using Domain.Services.Submission;

    public class SubmissionController : Controller
    {
        private readonly IEntityService<Submission> _submissionEntityService;
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IMapper _mapper;
        private readonly IRubricService _rubricService;
        private readonly ICardinalGradeService _cardinalGradeService;
        private readonly IEntityService<User> _userEntityService;
        private readonly IEntityService<CardinalGrade> _cardinalGradeEntityService;
        private readonly IEntityService<Task> _taskEntityService;

        private readonly ISubmissionService _submissionService;

        public SubmissionController(
            IEntityService<Submission> submissionEntityService,
            IUnitOfWorkFactory unitOfWorkFactory,
            IMapper mapper,
            IRubricService rubricService,
            ICardinalGradeService cardinalGradeService,
            IEntityService<User> userEntityService,
            IEntityService<CardinalGrade> cardinalGradeEntityService,
            IEntityService<Task> taskEntityService,
            ISubmissionService submissionService)
        {
            _submissionEntityService = submissionEntityService;
            _unitOfWorkFactory = unitOfWorkFactory;
            _mapper = mapper;
            _rubricService = rubricService;
            _cardinalGradeService = cardinalGradeService;
            _userEntityService = userEntityService;
            _cardinalGradeEntityService = cardinalGradeEntityService;
            _taskEntityService = taskEntityService;
            _submissionService = submissionService;
        }

        [HttpGet]
        public IActionResult Get(string id, int number)
        {
            Submission submission;
            List<Rubric> rubrics;
            CardinalGrade cardinalGrade;
            string[] answers;
            using (IUnitOfWork unitOfWork = _unitOfWorkFactory.Create())
            {
                var user = _userEntityService.Get(HttpContext.User.Identity.Name);
                submission = _submissionEntityService.Get(id);
                rubrics = _rubricService.GetRubricByTask(submission.Task.Id).ToList();
                cardinalGrade = _cardinalGradeService.GetCardinalGradeBySubmissionAndUser(submission, user);
                answers = new string[rubrics.Count];

                int i = 0;
                if (cardinalGrade != null)
                {
                    foreach (var answer in cardinalGrade.Answers)
                    {
                        answers[i] = $"{answer.Key.Id}_{answer.Value.Id}";
                        i++;
                    }
                }
                
                unitOfWork.Commit();
            }

            SubmissionViewModel model = _mapper.Map<SubmissionViewModel>(submission);
            model.Rubrics = rubrics;
            model.WorkNumber = number;
            model.CardinalGrade = cardinalGrade;
            model.Answers = answers;

            return View(model);
        }

        [HttpPost]
        public IActionResult Get(SubmissionViewModel viewModel)
        {
            Submission submission;

            using (IUnitOfWork unitOfWork = _unitOfWorkFactory.Create())
            {
                var user = _userEntityService.Get(HttpContext.User.Identity.Name);
                submission = _submissionEntityService.Get(viewModel.Id);
                var rubrics = _rubricService.GetRubricByTask(submission.Task.Id);
                var cardinalGrade = _cardinalGradeService.GetCardinalGradeBySubmissionAndUser(submission, user);

                if (cardinalGrade == null)
                {
                    cardinalGrade = new CardinalGrade(
                        user,
                        submission);
                }
                else
                {
                    _cardinalGradeEntityService.Delete(cardinalGrade.Id);
                }
                
                int points = 0;
                Dictionary<Rubric, RubricLevel> answers = new Dictionary<Rubric, RubricLevel>();
                foreach (var answer in viewModel.Answers)
                {
                    string[] str_answer = answer.Split('_');
                    var rubric = rubrics.FirstOrDefault(r => r.Id == str_answer[0]);
                    var rubricLevel = rubric.Levels.FirstOrDefault(rl => rl.Id == str_answer[1]);
                    points += rubricLevel.Points;
                    answers.Add(rubric, rubricLevel);
                }

                cardinalGrade.Grade = points;
                cardinalGrade.Answers = answers;
                cardinalGrade.InitializeId();
                _cardinalGradeEntityService.Add(cardinalGrade);

                unitOfWork.Commit();
            }

            return RedirectToRoute(new
            {
                controller = "Task",
                action = "Get",
                id = submission.Task.Id
            });
        }

        [HttpGet]
        public bool CalculateCardinalGrades(string id)
        {
            using (var unitOfWork = _unitOfWorkFactory.Create())
            {
                var task = _taskEntityService.Get(id);
                _cardinalGradeService.CalculateGrades(task, 0.8, 0.1);

                unitOfWork.Commit();
            }

            return true;
        }

        [HttpGet]
        public bool LoadGradesToMoodle(string id)
        {
            bool result = true;
            Task task = null;
            using (var unitOfWork = _unitOfWorkFactory.Create())
            {
                task = _taskEntityService.Get(id);
                

                unitOfWork.Commit();
            }

            result = _submissionService.LoadGradesToMoodle(task);

            return result;
        }
    }
}

WebApp/Views/Task/ErrorGrading.cshtml
<h2>К сожалению, ваши сокурсники загрузили слишком мало работ и вам нечего оценивать...</h2>

WebApp/Views/Task/Get.cshtml
@using WebApp.ViewModels
@using WebApp.Helpers
@model LargeTaskViewModel

<a class="btn btn-default btn-sm" asp-controller="Course" asp-action="Get" asp-route-id=@Model.CourseId><span class="glyphicon glyphicon-arrow-left"></span> Назад к списку заданий курса</a>
<h2>
    <img src="~/images/task_icon.svg" width="30" height="30" />Задание @Model.Name

    @if (Model != null)
    {
        if (Model.AllowSubmissionFromDate > DateTime.UtcNow)
        {
            <span class="label label-default">Недоступно</span>
        }
        if (Model.AllowSubmissionFromDate <= DateTime.UtcNow && Model.DueDate > DateTime.UtcNow)
        {
            <span class="label label-success">Доступно</span>
        }
        if (Model.DueDate <= DateTime.UtcNow && Model.GradingDate > DateTime.UtcNow)
        {
            <span class="label label-warning">Доступно для оценивания</span>
        }
        if (Model.GradingDate <= DateTime.UtcNow)
        {
            <span class="label label-danger">Закрыто</span>
        }
        if ((User.IsInRole("teacher") || User.IsInRole("admin")) && Model.DueDate > DateTime.UtcNow)
        {
            <br /><br /><a class="btn btn-default btn-lg" asp-controller="Task" asp-action="Settings" asp-route-task=@Model.Id><span class="glyphicon glyphicon-cog"></span> Редактировать настройки</a>
            if (Model.PeerGrading == Domain.Entities.PeerGradingEnum.Cardinal)
            {
                <br /><br /><a class="btn btn-default btn-lg" asp-controller="Rubric" asp-action="Get" asp-route-id="@Model.Id">
                    <span class="glyphicon glyphicon-align-justify"></span> Рубрики
                </a>
            }

        }
        if ((User.IsInRole("teacher") || User.IsInRole("admin")) && Model.GradingDate <= DateTime.UtcNow)
        {
            if (Model.PeerGrading == Domain.Entities.PeerGradingEnum.Ordinal)
            {
                <br /><br /><a class="btn btn-default btn-lg" id="btnCalculateOrdinal"><span class="glyphicon glyphicon-signal"></span> Вычислить оценки</a>
            }
            else
            {
                <br /><br /><a class="btn btn-default btn-lg" id="btnCalculateCardinal"><span class="glyphicon glyphicon-signal"></span> Вычислить оценки</a>
            }

            <br /><br /><a class="btn btn-default btn-lg" id="btnLoadGrades"><span class="moodle-icon"></span> Выгрузить оценки в Moodle</a>

        }
    }
</h2>
<br /><br />
<h5><b>Описание:</b></h5>
@Html.DisplayHtmlString(Model.Description)
<br />
<h5><b>Дата начала выполнения задания:</b> @Model.AllowSubmissionFromDate.ToLocalTime()</h5>
<br />
<h5><b>Дата окончания выполнения задания:</b> @Model.DueDate.ToLocalTime()</h5>
<br />
<h5><b>Дата окончания оценивания:</b> @Model.GradingDate.ToLocalTime()</h5>
<br />
@if (Model.AllowSubmissionFromDate <= DateTime.UtcNow && Model.DueDate > DateTime.UtcNow && User.IsInRole("student"))
            {
                if (!Model.IsAttachedSubmission)
                {
                    <h3>Загрузить ответ на задание</h3>
                    <form asp-action="AddFile" asp-controller="Task" method="post" enctype="multipart/form-data" asp-route-taskId=@Model.Id>
                        <div class="form-group">
                            <h5><b>Ответ в виде файла</b></h5><br>
                            <label class="errUpload" style="display: none" id="lblErrorUpload">Размер файла не должен превышать 2 мб!</label>
                            <input type="file" class="form-control" id="uploadedFile" name="uploadedFile"/><br>
                            <h5><b>Пояснение к ответу</b></h5><br>
                            <textarea name="textAnswer" cols="40" rows="5"></textarea><br>
                        </div>
                        <input type="submit" class="btn btn-success" value="Загрузить" id="btnUpload" disabled="disabled"/>
                    </form>
                    <br />
                    <br />
                }

            }

@if (User.IsInRole("student")
  && Model.DueDate <= DateTime.UtcNow
  && Model.GradingDate > DateTime.UtcNow)
{
    if (!Model.IsGradedSubmissions
        && Model.PeerGrading == Domain.Entities.PeerGradingEnum.Ordinal)
    {
        <a class="btn btn-default btn-lg" asp-controller="Task" asp-action="Grade" asp-route-taskId=@Model.Id><span class="glyphicon glyphicon-edit"></span> Оценить работы других студентов</a>    
    }
    if (Model.PeerGrading == Domain.Entities.PeerGradingEnum.Cardinal)
    {
        int i = 1;
        <h3>Работы на проверку:</h3>
        <table class="table table-hover">
            <tr>
                <th>
                    Работа
                </th>
                <th>
                    Статус
                </th>
            </tr>
            @foreach (var submission in Model.Submissions)
            {
                <tr>
                    <td>
                        <a asp-controller="Submission" asp-action="Get" asp-route-id="@submission.Id" asp-route-number="@i">Работа @i</a>
                    </td>
                    <td>
                        @if (Model.CardinalGrades.Exists(g => g.Submission.Id == submission.Id))
                        {
                            <span class="label label-success">Проверена</span>
                        }
                        else
                        {
                            <span class="label label-warning">Не проверена</span>
                        }
                    </td>
                </tr>
                i++;
            }
        </table>
    }
}

    <script type="text/javascript">
    $("#uploadedFile").change(function() {
        var maxFileSize = @Domain.Entities.File.MaxLengthBytes;
        var fileUpload = $('#uploadedFile');

        if (fileUpload.val() == '') {
            $('#btnUpload').prop('disabled', true);
            $("#lblErrorUpload").hide();
        } else {
            if (fileUpload[0].files[0].size < maxFileSize) {
                $('#btnUpload').prop('disabled', false);
                $("#lblErrorUpload").hide();
            } else {
                $('#btnUpload').prop('disabled', true);
                $("#lblErrorUpload").show();
            }
        }
    });

    $("#btnCalculateOrdinal").on(
        'click',
        function() {
            $.ajax({
                url: '/Task/CalculateGrades/@Model.Id',
                type: 'GET',
                dataType: 'json',
                Accept : "application/json",
                contentType: "application/json",
                success: function(data) {
                    alert("Оценки вычислены!");
                }
            });
        });
    $('#btnCalculateCardinal').on(
        'click',
        function() {
            $.ajax({
                url: '/Submission/CalculateCardinalGrades/@Model.Id',
                type: 'GET',
                dataType: 'json',
                Accept : "application/json",
                contentType: "application/json",
                success: function(data) {
                    alert("Оценки вычислены!");
                }
            });
        });
    $('#btnLoadGrades').on(
        'click',
        function() {
            $.ajax(
                {
                    url: '/Submission/LoadGradesToMoodle/@Model.Id',
                    type: 'GET',
                    dataType: 'json',
                    Accept: "application/json",
                    contentType: "application/json",
                    success: function (result) {
                        if (result) {
                            alert("Оценки выгружены!");
                        } else {
                            alert("Упс... что-то пошло не так. Попробуйте еще раз.");
                        }
                         
                    }
                });
        });
        </script>

WebApp/Views/Task/Grade.cshtml
@using System.Linq
@using WebApp.Helpers
@using WebApp.ViewModels
@model OrdinalGradeTaskViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a class="btn btn-default btn-sm" asp-controller="Task" asp-action="Get" asp-route-id=@Model.Id><span class="glyphicon glyphicon-arrow-left"></span> Назад к заданию</a>
<h2>Форма оценивания задания</h2>
<h5><b>Задание: </b> @Model.Name</h5>
<h5><b>Курс: </b> @Model.CourseName</h5>
<div class="row">
    @for (int i = 0; i < Model.DistributionFile.Count; i++) // Files.Count
    {
        <div class="col-md-2">
            <h4>Работа @Model.DistributionFile.ElementAt(i).Key.GraderWorkNumber </h4>
            <a class="btn btn-default btn-sm" asp-controller="File" asp-action="Download" asp-route-id="@Model.DistributionFile.ElementAt(i).Value.FileName" asp-route-number="@Model.DistributionFile.ElementAt(i).Key.GraderWorkNumber"><span class="glyphicon glyphicon-download-alt"></span> Скачать</a>
        </div>
    }
</div>
<form asp-controller="Task" asp-action="Grade" method="post">
    <div class="row">
        <h3>Оцените работы и расставьте в порядке убывания качества: </h3>
        <h4>Примечания:</h4>
        <h5>1. Лучшая работа в левом верхнем углу. </h5>
        <h5>2. Оценивание происходит слева направо, сверху вниз.</h5><br />
        
        @{
            for (int i=0;i<Model.DistributionFile.Count - 1;i++) //Files.Count - 1
            {
                
                 @Html.DisplayHtmlString("Работа")
                 
                 <select class="works" id=@("work" + (i + 1)) name=@("work" + (i + 1))>
                     <option value=" "> </option>
                     @foreach (var df in Model.DistributionFile)
                     {
                         <option value=@(df.Key.GraderWorkNumber)>@(df.Key.GraderWorkNumber)</option>
                         
                     }
                 </select>
                 <select class="grades" id=@("grade" + (i + 1).ToString()) name=@("grade" + (i + 1).ToString())>
                     <option value=" "> </option>
                     <option>Намного лучше, чем </option>
                     <option>Лучше, чем </option>
                     <option>Немного лучше, чем </option>
                     <option>Примерно на одном уровне с </option>
                 </select>
                 if (i % 2 == 1 && i != Model.DistributionFile.Count - 2) //Files.Count - 2
                 {
                     @Html.DisplayHtmlString("<br/>");
                 }
             }
        }
        Работа
        @{
            <select class="works" id=@("work" + Model.DistributionFile.Count) name=@("work" + Model.DistributionFile.Count)>
                <option value=" "> </option>
                @foreach(var df in Model.DistributionFile)
                {
                    <option value=@(df.Key.GraderWorkNumber)>@(df.Key.GraderWorkNumber)</option>;
                }
            </select>
        }
    </div>
    <div class="row" align="center">
        <br/><button class="btn btn-lg btn-primary" id="btnGrade" type="submit" disabled>Оценить</button>
    </div>
    @Html.HiddenFor(m => m.Id, Model.Id)
</form>


<script type="text/javascript">
    function change(event) {
        var numbers = [];
        $(".works").each(function () {
            if ($(this).val() !== "") {
                var num = $("option:selected", this).text();
                numbers.push(num);
            }
        });
        $(".works").each(function () {
            var selectObj = document.getElementById($(this).attr("id"));
            for (var i = 0; i < selectObj.length; i++) {
                if (numbers.indexOf(selectObj.options[i].text) == -1) {
                    selectObj.options[i].disabled = false;
                }
            }
            numbers.forEach(function(item, i, arr) {
                var option = $("option[value='" + item + "']", selectObj);
                option.attr("disabled", "disabled");
            });
        });
        }
    $(".works").change(function(event) {
            change(event);
            submitCheck();
        });
    $(".grades").change(function() {
        submitCheck();
    });
    function submitCheck() {
        var disabled = false;

        $(".works").each(function() {
            if ($(this).val() === "") {
                disabled = true;
            }
        });

        $(".grades").each(function () {
            if ($(this).val() === "") {
                disabled = true;
            }
        });

        document.getElementById("btnGrade").disabled = disabled;
    }
    function unDisable() {
        $(".works").each(function () {
            var selectObj = document.getElementById($(this).attr("id"));
            for (var i = 0; i < selectObj.length; i++) {
                selectObj.options[i].disabled = false;
            }
        });
    }

    $("#btnGrade").on('click',
        function() {
            unDisable();
        });

</script>

WebApp/Views/Task/Grades.cshtml
@model WebApp.ViewModels.GradesTaskViewModel


<a class="btn btn-default btn-sm" asp-controller="Task" asp-action="Get" asp-route-id=@Model.Id><span class="glyphicon glyphicon-arrow-left"></span> Назад к заданию</a>
<br /><h1>Оценки за задание @Model.Name</h1>

<table class="table table-hover">
    <tr>
        <th>
            Пользователь
        </th>
        <th>
            Оценка (из @Model.MaxGrade)
        </th>
    </tr>
    @foreach (var submission in Model.Submissions)
    {
        <tr>
            <td>
                @submission.User.Nickname
            </td>
            <td>
                @submission.SummaryGrade
            </td>
        </tr>
    }
</table>

WebApp/Views/Task/Settings.cshtml
@using Microsoft.AspNetCore.Mvc
@using Microsoft.AspNetCore.Mvc.Rendering
@using WebApp.ViewModels
@model TaskViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Настройки оценивания</h2>
<h4>Задание: @Model.Name</h4>
<h4>Курс: @Model.CourseName</h4>

<br />
<form method="post" asp-controller="Task" asp-action="Settings">
    <label for="maxworks">Количество назначаемых работ: </label>
    <select id="maxworks" name="maxworks" asp-for="MaxWorks">
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
    </select>
    <br /><input type="submit" value="Сохранить" class="btn btn-primary">
    @Html.HiddenFor(model => model.Id, null)
</form>